name: Slides

on:
  push:
    branches: [main]
    paths: [.doc/SLIDES.md, .github/workflows/slides.yml]
  workflow_dispatch:

# To preview slides: npx @marp-team/marp-cli .doc/SLIDES.md --watch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build slides
        run: npx --yes @marp-team/marp-cli .doc/SLIDES.md -o public/index.html --html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
